### ISSUE TITLE
what's the number of ISS

### ISSUE THREAD

**Issue by zuowang** [wenwei202/iss-rnns#2]
@wenwei202 

When I evaluated the model, the output of below line of code is 1098 for cell0 and 969 for cell1.
ptb/ptb_word_lm.py:204
```
print(sum(match_map==6))
```
Does that means the number of ISS is (1500 - 1098) and (1500 - 969)?

Thanks a lot!

**Comment by wenwei202** [comment]
Yes, correct. The plotted value is the number of removed components in ISS.

**Comment by zuowang** [comment]
Thanks!
