### ISSUE TITLE
Can not reproduce the experimental result in the paper

### ISSUE THREAD

**Issue by feiyuhug** [wenwei202/iss-rnns#9]
Hi,
Thanks for sharing your code. We tried to reproduce the ptb experiment, but can not get the results reported in the paper. It would be grateful if you could help us figure out what is going wrong.

Running the script provide in README

python ptb_word_lm.py --model sparselarge \
--data_path simple-examples/data/  \
--config_file structure_grouplasso.json 

We change the operation name from "_weights_" to "_kernel_" in _structure_grouplasso.json_ as mentioned in #8 , and set _freeze_mode_ to _element_ in the script. All other things are set as default.

We get the output mentioned in #2 as 825 for cell0 and 88 for cell1, which means there are 1500 - 825 ISS element for cell0 and 1500 - 88 for cell1 can be removed. The perplexity is 99.41 for val and 95.16 for test, which is far from the result reported in the paper.

The curves in tensorboard are shown below.

![image](https://user-images.githubusercontent.com/7116895/38136877-edcfb96c-3453-11e8-8e5a-c4a3f83158e6.png)

![image](https://user-images.githubusercontent.com/7116895/38136851-b38700b2-3453-11e8-8c04-14a4932e3908.png)

Thanks for taking your time!

**Comment by wenwei202** [comment]
The print numbers are the numbers of removed ISS components, which are consistent with the sparsity in the figure. Seems you are using a very high version of tensorflow. You may try to degrade down to tf 1.0 and try it.  You may need to adjust the hyperparameter `"global_decay": 0.00245`

**Comment by feiyuhug** [comment]
The problem is with the version of tensorflow, after degrading it to 1.0, everything works fine. Thank you!
